name: WakaTime Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: antx-code/readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMECODEFORSA }}
