name: WakaTime Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMECODEFORSA }}
