name: WakaTime Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 19 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: antx-code/antx-code@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMECODEFORSA }}
