name: WakaTime Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMECODESA }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
